# Generated by Django 5.0.1 on 2024-01-17 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_destino_fecha_publicacion_alter_user_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='destino',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Api.destino'),
        ),
    ]
