# Generated by Django 5.0.1 on 2024-01-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_destino_precio_alter_user_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
