# Generated by Django 5.0.1 on 2024-01-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_destino_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='precio',
        ),
        migrations.AddField(
            model_name='destino',
            name='sada',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
