# Generated by Django 5.0.1 on 2024-01-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_remove_destino_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
