# Generated by Django 5.0.1 on 2024-01-18 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_alter_user_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Api.destino'),
        ),
    ]
